import {
  User,
  Activity,
  ChatMessage,
  CampusEvent,
  Club,
  Complaint,
  CampusBuilding,
  NotificationItem,
  EmergencyAlert,
} from '../types';

export const mockUsers: User[] = [
  {
    id: 'usr-1',
    name: 'Aryan Sharma',
    email: 'aryan.sharma@campus.edu',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    studentId: '2023CSB1042',
    major: 'Computer Science & Engineering',
    year: '3rd Year (Junior)',
    isVerified: true,
    reliabilityScore: 96,
    activitiesAttended: 24,
    activitiesJoined: 25,
    badges: [
      { id: 'b1', name: 'Hackathon Champion', icon: '🏆', description: 'Won 1st place in HackCampus 2025' },
      { id: 'b2', name: 'Campus Guide', icon: '🧭', description: 'Organized 10+ student orientation walks' },
      { id: 'b3', name: 'Active Resolver', icon: '⚡', description: 'Resolved 5+ community care issues' },
      { id: 'b4', name: 'Reliable Squadmate', icon: '⭐', description: '95%+ attendance track record' },
    ],
    bio: 'CS Junior building distributed systems and AI agents. Always up for badminton, hackathons, and late-night filter coffee runs.',
    interests: ['Machine Learning', 'Next.js', 'Badminton', 'Hackathons', 'Sci-Fi Movies', 'Guitar'],
    role: 'student',
    privacySettings: {
      showEmail: true,
      showYear: true,
      allowDirectInvites: true,
    },
    karmaPoints: 480,
    joinedClubIds: ['club-1', 'club-2', 'club-5'],
  },
  {
    id: 'usr-2',
    name: 'Priya Patel',
    email: 'priya.patel@campus.edu',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    studentId: '2022ECB1015',
    major: 'Electronics & Communication',
    year: '4th Year (Senior)',
    isVerified: true,
    reliabilityScore: 98,
    activitiesAttended: 32,
    activitiesJoined: 33,
    badges: [
      { id: 'b5', name: 'Club Leader', icon: '👑', description: 'Lead Organizer at CodeNexus' },
      { id: 'b6', name: 'Mentor', icon: '💡', description: 'Mentored 20+ junior devs' },
    ],
    bio: 'Lead of CodeNexus club. Embedded systems + Web3 enthusiast. Contact for club collabs & workshops!',
    interests: ['Robotics', 'Web Development', 'Debating', 'Chess', 'Anime'],
    role: 'club_admin',
    privacySettings: {
      showEmail: true,
      showYear: true,
      allowDirectInvites: true,
    },
    karmaPoints: 720,
    joinedClubIds: ['club-1', 'club-3'],
  },
  {
    id: 'usr-3',
    name: 'Rohan Verma',
    email: 'rohan.verma@campus.edu',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    studentId: '2024MEB1090',
    major: 'Mechanical Engineering',
    year: '2nd Year (Sophomore)',
    isVerified: true,
    reliabilityScore: 92,
    activitiesAttended: 18,
    activitiesJoined: 20,
    badges: [
      { id: 'b7', name: 'Sports Captain', icon: '⚽', description: 'Host of weekly football scrims' },
    ],
    bio: 'Formula Student chassis designer by day, striker on the turf by night.',
    interests: ['Football', 'CAD Design', 'Rock Music', 'Table Tennis'],
    role: 'student',
    privacySettings: {
      showEmail: false,
      showYear: true,
      allowDirectInvites: true,
    },
    karmaPoints: 310,
    joinedClubIds: ['club-7', 'club-3'],
  },
  {
    id: 'usr-4',
    name: 'Ananya Sengupta',
    email: 'ananya.s@campus.edu',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    studentId: '2025DSB1008',
    major: 'Product Design & HCI',
    year: '1st Year (Freshman)',
    isVerified: true,
    reliabilityScore: 90,
    activitiesAttended: 8,
    activitiesJoined: 9,
    badges: [
      { id: 'b8', name: 'Creative Spark', icon: '🎨', description: 'Published 3 UI design kits' },
    ],
    bio: 'Freshman curious about UX design and campus theater. Finding my way around campus with CampusConnect!',
    interests: ['UI/UX Design', 'Photography', 'Theater', 'Indie Music'],
    role: 'student',
    privacySettings: {
      showEmail: true,
      showYear: true,
      allowDirectInvites: true,
    },
    karmaPoints: 190,
    joinedClubIds: ['club-4', 'club-5', 'club-6'],
  },
  {
    id: 'usr-5',
    name: 'Dr. K. Raman',
    email: 'admin.dean@campus.edu',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    studentId: 'FACULTY-042',
    major: 'Campus Affairs & Student Welfare',
    year: 'Dean / Administrative Head',
    isVerified: true,
    reliabilityScore: 100,
    activitiesAttended: 50,
    activitiesJoined: 50,
    badges: [
      { id: 'b9', name: 'Campus Administrator', icon: '🛡️', description: 'Official College Facilities Dean' },
    ],
    bio: 'Dean of Student Welfare & Campus Infrastructure. Overseeing Campus Care, event clearances, and student safety.',
    interests: ['Campus Infrastructure', 'Student Safety', 'Sustainable Green Campus'],
    role: 'campus_admin',
    privacySettings: {
      showEmail: true,
      showYear: true,
      allowDirectInvites: false,
    },
    karmaPoints: 1200,
    joinedClubIds: [],
  },
];

export const mockCampusBuildings: CampusBuilding[] = [
  {
    id: 'bldg-1',
    name: 'Turing Computer Science Hub',
    code: 'CS-BLOCK',
    category: 'academic',
    position: { x: 30, y: 25 },
    size: { width: 14, height: 12 },
    floors: 5,
    description: 'Home to Department of Computer Science & AI Labs, High-Performance Computing cluster, and VR Sandbox.',
    image: 'https://images.unsplash.com/photo-1562774053-701939374585?w=600&auto=format&fit=crop&q=80',
    rooms: [
      { name: 'Ada Lovelace Auditorium (Ground Floor)', floor: 1, category: 'Auditorium' },
      { name: 'AI & Robotics Research Lab 204', floor: 2, category: 'Lab' },
      { name: 'Cloud Computing Lab 305', floor: 3, category: 'Lab' },
      { name: 'HPC Cluster & Server Room 401', floor: 4, category: 'Research' },
      { name: 'Open Collaboration Studio 502', floor: 5, category: 'Study' },
    ],
    amenities: ['1 Gbps Wi-Fi', '24/7 Coding Pods', 'Vending Machines', 'Water Refill Stations'],
    wifiRating: 5,
    openHours: 'Open 24/7 for CS Students',
    activeComplaintsCount: 1,
  },
  {
    id: 'bldg-2',
    name: 'Aryabhata Science & Engineering Complex',
    code: 'ENGG-MAIN',
    category: 'academic',
    position: { x: 52, y: 22 },
    size: { width: 16, height: 14 },
    floors: 6,
    description: 'Central lecture theaters, Electronics Labs, Physics & Chemistry Research Halls, and Dean Office.',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=600&auto=format&fit=crop&q=80',
    rooms: [
      { name: 'Lecture Hall Complex A1-A4', floor: 1, category: 'Classrooms' },
      { name: 'VLSI & IoT Microelectronics Lab 210', floor: 2, category: 'Lab' },
      { name: 'Nanomaterials Testing Bay 312', floor: 3, category: 'Research' },
      { name: 'Faculty Conference Hall 501', floor: 5, category: 'Conference' },
    ],
    amenities: ['Central Air-Conditioning', 'Projector Theaters', 'Elevators', 'Accessible Ramps'],
    wifiRating: 4,
    openHours: '07:30 AM - 09:00 PM',
    activeComplaintsCount: 2,
  },
  {
    id: 'bldg-3',
    name: 'Ramanujan Central Library',
    code: 'LIB-CENTRAL',
    category: 'library',
    position: { x: 42, y: 44 },
    size: { width: 15, height: 13 },
    floors: 4,
    description: 'State-of-the-art 4-story knowledge center with over 150,000 volumes, private study carrels, and digital archives.',
    image: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=600&auto=format&fit=crop&q=80',
    rooms: [
      { name: 'Silent Study Atrium & Issue Desk', floor: 1, category: 'Reading' },
      { name: 'Periodicals & Journal Archive', floor: 2, category: 'Archive' },
      { name: 'Group Discussion Cubicles (Bookable)', floor: 3, category: 'Discussion' },
      { name: 'Digital Media & E-Library Terminal', floor: 4, category: 'Digital' },
    ],
    amenities: ['Ultra-Quiet Zone', 'High-Speed Wi-Fi', 'Book Scanner Stations', 'Cafe Kiosk'],
    wifiRating: 5,
    openHours: '08:00 AM - 02:00 AM (24h during exams)',
    activeComplaintsCount: 0,
  },
  {
    id: 'bldg-4',
    name: 'Annapoorna Central Food Court',
    code: 'FOOD-COURT',
    category: 'food',
    position: { x: 68, y: 45 },
    size: { width: 13, height: 11 },
    floors: 2,
    description: 'Multi-cuisine campus dining hub featuring subway counters, fresh juice stalls, bakery, and open terrace seating.',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&auto=format&fit=crop&q=80',
    rooms: [
      { name: 'Main Dining Hall & Live Counters', floor: 1, category: 'Dining' },
      { name: 'Midnight Canteen & Rooftop Deck', floor: 2, category: 'Cafe' },
    ],
    amenities: ['Outdoor Seating', 'Digital Kiosks', 'Cashless Payments', 'Handwash Bays'],
    wifiRating: 4,
    openHours: '07:00 AM - 01:30 AM',
    activeComplaintsCount: 1,
  },
  {
    id: 'bldg-5',
    name: 'Student Activity Center (SAC)',
    code: 'SAC-MAIN',
    category: 'sports',
    position: { x: 22, y: 55 },
    size: { width: 14, height: 13 },
    floors: 3,
    description: 'Vibrant hub for all club meetings, indoor sports (badminton, squash, table tennis), gym, and music rehearsal suites.',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&auto=format&fit=crop&q=80',
    rooms: [
      { name: 'Indoor Wooden Badminton Courts (4)', floor: 1, category: 'Sports' },
      { name: 'Dance & Theater Blackbox Studio 201', floor: 2, category: 'Arts' },
      { name: 'Club Executive War Rooms 205-208', floor: 2, category: 'Clubs' },
      { name: 'Gymnasium & Fitness Center', floor: 3, category: 'Fitness' },
    ],
    amenities: ['Locker Rooms', 'Showers', 'Equipment Rental', 'Soundproof Music Room'],
    wifiRating: 4,
    openHours: '06:00 AM - 10:30 PM',
    activeComplaintsCount: 0,
  },
  {
    id: 'bldg-6',
    name: 'Olympic Sports Arena & Turf Ground',
    code: 'SPORTS-TURF',
    category: 'sports',
    position: { x: 18, y: 78 },
    size: { width: 18, height: 15 },
    floors: 1,
    description: 'FIFA-grade synthetic football turf, 400m athletic track, floodlit basketball courts, and tennis arena.',
    image: 'https://images.unsplash.com/photo-1529900748604-07564a03e7a6?w=600&auto=format&fit=crop&q=80',
    rooms: [
      { name: 'Main Football Turf', floor: 1, category: 'Field' },
      { name: 'Basketball Courts 1 & 2', floor: 1, category: 'Courts' },
      { name: 'Cricket Practice Nets', floor: 1, category: 'Field' },
    ],
    amenities: ['Night Floodlights', 'First Aid Station', 'Grandstand 1500 Seats', 'Water Coolers'],
    wifiRating: 3,
    openHours: '05:30 AM - 11:00 PM',
    activeComplaintsCount: 1,
  },
  {
    id: 'bldg-7',
    name: 'Raman Boys Hostel Blocks (A & B)',
    code: 'HOSTEL-RAMAN',
    category: 'hostel',
    position: { x: 74, y: 20 },
    size: { width: 14, height: 14 },
    floors: 7,
    description: 'Residential quarters for 800+ male students with common lounges, laundry hubs, and study rooms on each floor.',
    image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600&auto=format&fit=crop&q=80',
    rooms: [
      { name: 'Common Mess Dining Hall', floor: 1, category: 'Mess' },
      { name: 'Recreation & TT Lounge', floor: 2, category: 'Lounge' },
      { name: 'Study Room 4th Floor', floor: 4, category: 'Study' },
    ],
    amenities: ['Laundry Room', 'Night Canteen', 'High-Speed Wi-Fi', '24/7 Security Guard Desk'],
    wifiRating: 3,
    openHours: '24/7 (Biometric Gate)',
    activeComplaintsCount: 3,
  },
  {
    id: 'bldg-8',
    name: 'Sarojini Girls Hostel Blocks (C & D)',
    code: 'HOSTEL-SAROJINI',
    category: 'hostel',
    position: { x: 78, y: 70 },
    size: { width: 14, height: 14 },
    floors: 7,
    description: 'Residential campus for 800+ female students featuring lush internal courtyards, badminton court, and study pods.',
    image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600&auto=format&fit=crop&q=80',
    rooms: [
      { name: 'Sarojini Mess Hall', floor: 1, category: 'Mess' },
      { name: 'Reading & Yoga Hall 2nd Floor', floor: 2, category: 'Wellness' },
      { name: 'Courtyard Badminton Bay', floor: 1, category: 'Sports' },
    ],
    amenities: ['Biometric Access', 'Indoor Gym', 'Laundry Service', '24/7 Medical Attendant'],
    wifiRating: 4,
    openHours: '24/7 (Biometric Gate)',
    activeComplaintsCount: 2,
  },
  {
    id: 'bldg-9',
    name: 'Innovation & Incubator Makerspace',
    code: 'MAKERSPACE',
    category: 'lab',
    position: { x: 45, y: 74 },
    size: { width: 13, height: 12 },
    floors: 3,
    description: 'Hardware prototyping playground equipped with 3D printers, laser cutters, PCB milling, and startup incubation bays.',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    rooms: [
      { name: 'Rapid Prototyping & 3D Print Lab 101', floor: 1, category: 'Hardware' },
      { name: 'Drone & Autonomous Systems Cage 202', floor: 2, category: 'Robotics' },
      { name: 'Startup Pitch Deck & Incubator Bay 301', floor: 3, category: 'Startup' },
    ],
    amenities: ['Industrial Tools', 'Soldering Stations', 'Mentorship Desk', 'High-Speed Fibre'],
    wifiRating: 5,
    openHours: '09:00 AM - 12:00 Midnight',
    activeComplaintsCount: 0,
  },
  {
    id: 'bldg-10',
    name: 'Campus Health & Wellness Center',
    code: 'HEALTH-MED',
    category: 'medical',
    position: { x: 50, y: 92 },
    size: { width: 11, height: 9 },
    floors: 2,
    description: 'Round-the-clock medical care, pharmacy, emergency ambulance bay, counseling & psychological support suites.',
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&auto=format&fit=crop&q=80',
    rooms: [
      { name: 'Emergency Triage & Consultation OPD', floor: 1, category: 'Medical' },
      { name: '24/7 Campus Pharmacy', floor: 1, category: 'Pharmacy' },
      { name: 'Mental Health & Counseling Suites', floor: 2, category: 'Counseling' },
    ],
    amenities: ['24/7 Ambulance Bay', 'Doctor on Call', 'Emergency Beds', 'Free Basic Meds'],
    wifiRating: 4,
    openHours: '24 Hours Open',
    activeComplaintsCount: 0,
  },
  {
    id: 'bldg-11',
    name: 'Central Administration Secretariat',
    code: 'ADMIN-HQ',
    category: 'admin',
    position: { x: 30, y: 40 },
    size: { width: 12, height: 11 },
    floors: 4,
    description: 'Offices of the Chancellor, Registrar, Finance Division, Campus Care Grievance Cell, and Student Affairs.',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&auto=format&fit=crop&q=80',
    rooms: [
      { name: 'Student Services Helpdesk & Tokens', floor: 1, category: 'Helpdesk' },
      { name: 'Campus Care Resolution Cell Room 104', floor: 1, category: 'Campus Care' },
      { name: 'Dean of Student Welfare Office 201', floor: 2, category: 'Administration' },
    ],
    amenities: ['Document Verification Counters', 'Payment Kiosks', 'Meeting Chambers'],
    wifiRating: 5,
    openHours: '09:00 AM - 05:30 PM',
    activeComplaintsCount: 0,
  },
];

export const mockActivities: Activity[] = [
  {
    id: 'act-1',
    title: 'Football 7v7 Under the Floodlights ⚽',
    description: 'Casual friendly match at the Olympic turf. Need 4 more players for full 7v7 squad! All skill levels welcome, bibs provided.',
    category: 'sports',
    creatorId: 'usr-3',
    creatorName: 'Rohan Verma',
    creatorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    minParticipants: 10,
    maxParticipants: 14,
    participants: [
      { userId: 'usr-3', userName: 'Rohan Verma', userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80', role: 'host', joinedAt: '2026-08-10 10:00' },
      { userId: 'usr-1', userName: 'Aryan Sharma', userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80', role: 'member', joinedAt: '2026-08-10 10:30' },
      { userId: 'usr-4', userName: 'Ananya Sengupta', userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80', role: 'member', joinedAt: '2026-08-10 10:45' },
    ],
    date: 'Today, 6:30 PM',
    time: '6:30 PM - 8:00 PM',
    locationName: 'Olympic Turf Ground (Pitch A)',
    buildingId: 'bldg-6',
    coordinates: { x: 18, y: 78 },
    status: 'open',
    tags: ['Football', 'Fitness', 'EveningSports', 'Casual'],
    chatId: 'chat-act-1',
    createdAt: '2026-08-10 09:30',
    requiredSkillLevel: 'all',
  },
  {
    id: 'act-2',
    title: 'Smart India Hackathon: Frontend & UI Lead Wanted 🚀',
    description: 'Forming a killer 6-person squad for SIH 2026 problem statement on AI-assisted agricultural monitoring. We already have 2 ML engineers and 1 backend dev. Need a React/Next.js UI wizard!',
    category: 'hackathon',
    creatorId: 'usr-1',
    creatorName: 'Aryan Sharma',
    creatorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    minParticipants: 4,
    maxParticipants: 6,
    participants: [
      { userId: 'usr-1', userName: 'Aryan Sharma', userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80', role: 'host', joinedAt: '2026-08-09 18:00' },
      { userId: 'usr-2', userName: 'Priya Patel', userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80', role: 'member', joinedAt: '2026-08-09 19:15' },
      { userId: 'usr-4', userName: 'Ananya Sengupta', userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80', role: 'member', joinedAt: '2026-08-10 08:30' },
    ],
    date: 'Tomorrow, 5:00 PM',
    time: '5:00 PM - 7:30 PM',
    locationName: 'Turing CS Hub - Room 502 Studio',
    buildingId: 'bldg-1',
    coordinates: { x: 30, y: 25 },
    status: 'open',
    tags: ['Hackathon', 'React', 'Nextjs', 'AI', 'SIH2026'],
    chatId: 'chat-act-2',
    createdAt: '2026-08-09 18:00',
    requiredSkillLevel: 'intermediate',
  },
  {
    id: 'act-3',
    title: 'Operating Systems Mid-Term Prep Sprint 📚',
    description: 'Covering Virtual Memory, Deadlocks, and Disk Scheduling with past 5 years question papers. Bringing whiteboard markers and solved notes!',
    category: 'study',
    creatorId: 'usr-2',
    creatorName: 'Priya Patel',
    creatorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    minParticipants: 3,
    maxParticipants: 8,
    participants: [
      { userId: 'usr-2', userName: 'Priya Patel', userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80', role: 'host', joinedAt: '2026-08-08 14:00' },
      { userId: 'usr-1', userName: 'Aryan Sharma', userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80', role: 'member', joinedAt: '2026-08-08 15:20' },
    ],
    date: 'Tonight, 8:00 PM',
    time: '8:00 PM - 11:00 PM',
    locationName: 'Ramanujan Library - Discussion Cubicle 3B',
    buildingId: 'bldg-3',
    coordinates: { x: 42, y: 44 },
    status: 'open',
    tags: ['OS', 'ExamPrep', 'CSE', 'StudyGroup'],
    chatId: 'chat-act-3',
    createdAt: '2026-08-08 14:00',
    requiredSkillLevel: 'all',
  },
  {
    id: 'act-4',
    title: 'Badminton Doubles Match 🏸',
    description: 'Need 1 player to complete our 4-player doubles roster at SAC wooden court #2. Yonex Mavis 350 shuttles ready.',
    category: 'sports',
    creatorId: 'usr-1',
    creatorName: 'Aryan Sharma',
    creatorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    minParticipants: 4,
    maxParticipants: 4,
    participants: [
      { userId: 'usr-1', userName: 'Aryan Sharma', userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80', role: 'host', joinedAt: '2026-08-10 07:00' },
      { userId: 'usr-3', userName: 'Rohan Verma', userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80', role: 'member', joinedAt: '2026-08-10 07:30' },
      { userId: 'usr-2', userName: 'Priya Patel', userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80', role: 'member', joinedAt: '2026-08-10 08:10' },
    ],
    date: 'Today, 5:00 PM',
    time: '5:00 PM - 6:30 PM',
    locationName: 'SAC Indoor Badminton Court 2',
    buildingId: 'bldg-5',
    coordinates: { x: 22, y: 55 },
    status: 'open',
    tags: ['Badminton', 'Fitness', 'SAC'],
    chatId: 'chat-act-4',
    createdAt: '2026-08-10 07:00',
    requiredSkillLevel: 'intermediate',
  },
];

export const mockChatMessages: Record<string, ChatMessage[]> = {
  'chat-act-1': [
    {
      id: 'msg-1',
      chatId: 'chat-act-1',
      senderId: 'system',
      senderName: 'CampusConnect Bot',
      senderAvatar: '/bot.png',
      content: '🎉 Minimum participants reached! Group squad chat is now active for Football 7v7.',
      timestamp: '10:45 AM',
      type: 'system',
    },
    {
      id: 'msg-2',
      chatId: 'chat-act-1',
      senderId: 'usr-3',
      senderName: 'Rohan Verma',
      senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      content: 'Hey everyone! I have got the match ball and yellow/blue bibs. See you at Pitch A around 6:15 PM to warm up!',
      timestamp: '10:48 AM',
      type: 'text',
    },
    {
      id: 'msg-3',
      chatId: 'chat-act-1',
      senderId: 'usr-1',
      senderName: 'Aryan Sharma',
      senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      content: 'Awesome! Bringing stud shoes and water bottles. Is floodlight booking confirmed?',
      timestamp: '10:52 AM',
      type: 'text',
    },
    {
      id: 'msg-4',
      chatId: 'chat-act-1',
      senderId: 'usr-3',
      senderName: 'Rohan Verma',
      senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      content: 'Yes, sports secretary confirmed slot till 8:30 PM!',
      timestamp: '10:55 AM',
      type: 'text',
    },
  ],
  'chat-act-2': [
    {
      id: 'msg-201',
      chatId: 'chat-act-2',
      senderId: 'system',
      senderName: 'CampusConnect Bot',
      senderAvatar: '/bot.png',
      content: '🚀 Smart India Hackathon Squad initialized. Coordinate problem statement breakdown here.',
      timestamp: 'Yesterday 7:00 PM',
      type: 'system',
    },
    {
      id: 'msg-202',
      chatId: 'chat-act-2',
      senderId: 'usr-1',
      senderName: 'Aryan Sharma',
      senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      content: 'Welcome team! We are building an IoT crop disease prediction web app with computer vision backend. @Ananya can you help review the Figma mockups?',
      timestamp: 'Yesterday 7:15 PM',
      type: 'text',
    },
    {
      id: 'msg-203',
      chatId: 'chat-act-2',
      senderId: 'usr-4',
      senderName: 'Ananya Sengupta',
      senderAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
      content: 'Already started! Working on a clean dark dashboard with field telemetry maps. Will present draft at 5 PM in Room 502.',
      timestamp: 'Today 8:35 AM',
      type: 'text',
    },
  ],
  'chat-act-4': [
    {
      id: 'msg-401',
      chatId: 'chat-act-4',
      senderId: 'system',
      senderName: 'CampusConnect Bot',
      senderAvatar: '/bot.png',
      content: '🏸 Badminton Doubles Squad created. 3/4 confirmed.',
      timestamp: '08:15 AM',
      type: 'system',
    },
    {
      id: 'msg-402',
      chatId: 'chat-act-4',
      senderId: 'usr-1',
      senderName: 'Aryan Sharma',
      senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      content: 'Court #2 booked under student ID 2023CSB1042. Need just 1 more player!',
      timestamp: '08:20 AM',
      type: 'text',
    },
  ],
};

export const mockEvents: CampusEvent[] = [
  {
    id: 'evt-1',
    title: 'HackNova 2026: 36-Hour National Campus Hackathon 💻🔥',
    description: 'The flagship annual hackathon of CampusConnect ecosystem with ₹3,00,000 prize pool! Tracks include AI Agents, Smart Campus, Web3 & FinTech, and Green Tech. Free food, swag packs, and mentorship from Google & Microsoft engineers.',
    organizer: 'CodeNexus & GDSC Campus',
    clubId: 'club-1',
    category: 'hackathon',
    bannerImage: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&auto=format&fit=crop&q=80',
    date: 'Aug 22 - Aug 24, 2026',
    time: 'Friday 06:00 PM onwards',
    locationName: 'Ada Lovelace Auditorium, Turing CS Hub',
    buildingId: 'bldg-1',
    coordinates: { x: 30, y: 25 },
    rsvpCount: 248,
    rsvpUserIds: ['usr-1', 'usr-2', 'usr-3', 'usr-4'],
    bookmarkedUserIds: ['usr-1', 'usr-4'],
    tags: ['Hackathon', 'CashPrize', 'AI', 'Networking', 'FreeFood'],
    isFeatured: true,
    capacity: 350,
    deadline: 'Aug 18, 2026',
  },
  {
    id: 'evt-2',
    title: 'Google DeepMind & Gemini AI Engineering Workshop 🤖',
    description: 'Hands-on masterclass on building autonomous agent workflows with Gemini APIs, Function Calling, and Antigravity SDK. Bring your laptops with Node.js installed.',
    organizer: 'Google Developer Student Club (GDSC)',
    clubId: 'club-2',
    category: 'workshop',
    bannerImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
    date: 'Aug 15, 2026',
    time: '02:00 PM - 05:30 PM',
    locationName: 'AI & Robotics Lab 204, CS Hub',
    buildingId: 'bldg-1',
    coordinates: { x: 30, y: 25 },
    rsvpCount: 165,
    rsvpUserIds: ['usr-1', 'usr-2'],
    bookmarkedUserIds: ['usr-1'],
    tags: ['AI', 'Gemini', 'Google', 'HandsOn', 'Certificates'],
    isFeatured: true,
    capacity: 180,
  },
  {
    id: 'evt-3',
    title: 'Vibrance 2026: Campus Cultural Pro-Nite & Battle of Bands 🎸',
    description: 'Get ready for the biggest night of the semester! Featuring headlining indie band ‘The Local Train’ live on the main amphitheater stage, food stalls, carnival games, and DJ night.',
    organizer: 'Campus Cultural Council & Abhinaya Society',
    clubId: 'club-4',
    category: 'fest',
    bannerImage: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop&q=80',
    date: 'Sep 05, 2026',
    time: '06:00 PM - 11:30 PM',
    locationName: 'Olympic Arena Grand Amphitheater',
    buildingId: 'bldg-6',
    coordinates: { x: 18, y: 78 },
    rsvpCount: 890,
    rsvpUserIds: ['usr-1', 'usr-3', 'usr-4'],
    bookmarkedUserIds: ['usr-2', 'usr-4'],
    tags: ['Cultural', 'Music', 'LiveBand', 'CampusLife', 'ProNite'],
    isFeatured: true,
    capacity: 2500,
  },
  {
    id: 'evt-4',
    title: 'Microsoft SDE & Cloud Internship Fast-Track Drive 💼',
    description: 'Pre-placement talk and coding assessment breakdown for Summer 2027 Software Engineering internships. Eligibility: 2nd and 3rd year B.Tech students with CGPA >= 7.5.',
    organizer: 'College Training & Placement Cell (T&P)',
    category: 'internship',
    bannerImage: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop&q=80',
    date: 'Aug 19, 2026',
    time: '10:00 AM - 01:00 PM',
    locationName: 'Aryabhata Complex - Main Lecture Hall A1',
    buildingId: 'bldg-2',
    coordinates: { x: 52, y: 22 },
    rsvpCount: 420,
    rsvpUserIds: ['usr-1', 'usr-2'],
    bookmarkedUserIds: ['usr-1'],
    tags: ['Internship', 'Microsoft', 'Placements', 'HighStipend'],
    deadline: 'Aug 17, 2026',
  },
  {
    id: 'evt-5',
    title: 'RoboWars 2026: Combat Bot Championship ⚙️',
    description: 'Witness 15kg & 30kg combat bots battle it out in a bulletproof polycarbonate arena with spinning blades, pneumatic flippers, and flamethrowers!',
    organizer: 'RoboTech Society',
    clubId: 'club-3',
    category: 'hackathon',
    bannerImage: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop&q=80',
    date: 'Aug 29, 2026',
    time: '11:00 AM - 06:00 PM',
    locationName: 'Innovation Makerspace Arena Bay',
    buildingId: 'bldg-9',
    coordinates: { x: 45, y: 74 },
    rsvpCount: 310,
    rsvpUserIds: ['usr-2', 'usr-3'],
    bookmarkedUserIds: ['usr-3'],
    tags: ['Robotics', 'Hardware', 'Combat', 'Makerspace'],
  },
  {
    id: 'evt-6',
    title: 'TEDxCampus: Breaking Frontiers of Human Potential 🎤',
    description: '12 visionary speakers from space tech, climate science, neurotechnology, and social entrepreneurship sharing 18-minute world-changing talks.',
    organizer: 'TEDx Student Chapter',
    category: 'seminar',
    bannerImage: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=800&auto=format&fit=crop&q=80',
    date: 'Sep 12, 2026',
    time: '09:30 AM - 04:30 PM',
    locationName: 'Ada Lovelace Auditorium, CS Hub',
    buildingId: 'bldg-1',
    coordinates: { x: 30, y: 25 },
    rsvpCount: 290,
    rsvpUserIds: ['usr-4'],
    bookmarkedUserIds: ['usr-1', 'usr-4'],
    tags: ['TEDx', 'Inspiration', 'Leadership', 'Talks'],
  },
];

export const mockClubs: Club[] = [
  {
    id: 'club-1',
    name: 'CodeNexus — Computer Science & Open Source Guild',
    tagLine: 'Code. Ship. Scale. Repeat.',
    description: 'Premier student developer community fostering open-source software, competitive programming, Web3, and cloud computing. We host national hackathons, weekly code sprints, and FAANG interview prep cohorts.',
    category: 'technical',
    logo: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
    memberCount: 340,
    leadName: 'Priya Patel',
    leadEmail: 'priya.patel@campus.edu',
    members: [
      { userId: 'usr-2', userName: 'Priya Patel', role: 'lead', joinedAt: '2023-08-01' },
      { userId: 'usr-1', userName: 'Aryan Sharma', role: 'core', joinedAt: '2024-01-15' },
    ],
    announcements: [
      {
        id: 'ann-1',
        clubId: 'club-1',
        clubName: 'CodeNexus',
        clubLogo: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=150&auto=format&fit=crop&q=80',
        title: '🔥 HackNova 2026 Problem Statements are LIVE!',
        content: 'Check out the 4 competitive tracks on our portal. Registrations close in 7 days. Free AWS credits for all registered teams!',
        date: '2 hours ago',
        likes: 42,
        likedByUserIds: ['usr-1', 'usr-4'],
        badge: 'Priority Announcement',
      },
      {
        id: 'ann-2',
        clubId: 'club-1',
        clubName: 'CodeNexus',
        clubLogo: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=150&auto=format&fit=crop&q=80',
        title: 'Weekly Algorithmic Sprint #14 Results',
        content: 'Congrats to Aryan Sharma and Tanmay Das for topping the LeetCode Hard contest leaderboard this Sunday!',
        date: 'Yesterday',
        likes: 28,
        likedByUserIds: ['usr-1', 'usr-2'],
      },
    ],
    recruitment: {
      isOpen: true,
      title: 'Fall 2026 Core Team & Sub-Lead Inductions',
      roles: ['Full-Stack Dev', 'AI/ML Researcher', 'Event Operations Lead', 'Graphic Designer'],
      deadline: 'Aug 20, 2026',
      applicants: [
        {
          id: 'app-1',
          userId: 'usr-4',
          userName: 'Ananya Sengupta',
          userEmail: 'ananya.s@campus.edu',
          userMajor: 'Product Design & HCI',
          userYear: '1st Year',
          roleApplied: 'Graphic Designer',
          whyJoin: 'I have 2 years of experience designing posters and UI kits for student hackathons in high school. Excited to revamp CodeNexus brand aesthetics!',
          portfolioUrl: 'https://behance.net/ananyas',
          status: 'shortlisted',
          appliedAt: '2026-08-09 14:30',
        },
      ],
    },
  },
  {
    id: 'club-2',
    name: 'Google Developer Student Club (GDSC)',
    tagLine: 'Bridge the gap between theory and industry practice.',
    description: 'Official Google-backed developer community on campus. We run Solution Challenge hackathons, Android / Flutter study jams, and cloud certification bootcamps.',
    category: 'technical',
    logo: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&auto=format&fit=crop&q=80',
    memberCount: 420,
    leadName: 'Tanvi Agarwal',
    leadEmail: 'tanvi.gdsc@campus.edu',
    members: [
      { userId: 'usr-1', userName: 'Aryan Sharma', role: 'member', joinedAt: '2024-02-10' },
    ],
    announcements: [
      {
        id: 'ann-3',
        clubId: 'club-2',
        clubName: 'GDSC Campus',
        clubLogo: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=150&auto=format&fit=crop&q=80',
        title: '🤖 Google Cloud Study Jam 2026: Swag Kits Dispatched!',
        content: 'Students who completed the GenAI Arcade badges can collect their physical Google backpacks and pins from CS Hub Room 204 today.',
        date: '1 day ago',
        likes: 65,
        likedByUserIds: ['usr-1', 'usr-3'],
      },
    ],
    recruitment: {
      isOpen: false,
      title: 'Spring Drive Completed',
      roles: [],
      deadline: 'Closed',
      applicants: [],
    },
  },
  {
    id: 'club-3',
    name: 'RoboTech Society & Automation Guild',
    tagLine: 'From Silicon to Steel — Building Autonomous Machines.',
    description: 'Hardware enthusiasts crafting all-terrain rovers, autonomous drones, combat bots, and IoT smart campus sensors. Active in Robocon and World Robot Olympiad.',
    category: 'technical',
    logo: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    memberCount: 185,
    leadName: 'Vikramaditya Nair',
    leadEmail: 'vikram.robo@campus.edu',
    members: [
      { userId: 'usr-3', userName: 'Rohan Verma', role: 'member', joinedAt: '2024-09-01' },
      { userId: 'usr-2', userName: 'Priya Patel', role: 'member', joinedAt: '2023-09-10' },
    ],
    announcements: [
      {
        id: 'ann-4',
        clubId: 'club-3',
        clubName: 'RoboTech',
        clubLogo: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=150&auto=format&fit=crop&q=80',
        title: '⚙️ 3D Printers Available for Open Projects this Weekend',
        content: 'Innovation Makerspace SLA and FDM printers will be free for all verified RoboTech members this Saturday from 10 AM to 6 PM.',
        date: '3 days ago',
        likes: 31,
        likedByUserIds: ['usr-3'],
      },
    ],
    recruitment: {
      isOpen: true,
      title: 'Robocon 2027 Squad Recruitment',
      roles: ['ROS2 Developer', 'CAD & Mechanical Specialist', 'PCB Layout Designer'],
      deadline: 'Aug 25, 2026',
      applicants: [],
    },
  },
  {
    id: 'club-4',
    name: 'Abhinaya — Dramatics & Street Play Society',
    tagLine: 'Express. Provoke. Inspire.',
    description: 'Stage plays, street nukkad nataks, improv comedy, and voice acting. Champion team across national collegiate theater fests.',
    category: 'cultural',
    logo: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1460723237483-7a6dc9d0b212?w=800&auto=format&fit=crop&q=80',
    memberCount: 120,
    leadName: 'Meera Deshmukh',
    leadEmail: 'meera.drama@campus.edu',
    members: [
      { userId: 'usr-4', userName: 'Ananya Sengupta', role: 'member', joinedAt: '2025-08-15' },
    ],
    announcements: [
      {
        id: 'ann-5',
        clubId: 'club-4',
        clubName: 'Abhinaya Drama',
        clubLogo: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=150&auto=format&fit=crop&q=80',
        title: '🎭 Auditions for Vibrance 2026 Main Stage Musical',
        content: 'Auditions happening tomorrow at SAC Studio 201. Monologue scripts available at the desk or bring your own piece!',
        date: 'Yesterday',
        likes: 54,
        likedByUserIds: ['usr-4'],
      },
    ],
    recruitment: {
      isOpen: true,
      title: 'Actors, Scriptwriters & Stage Technicians Auditions',
      roles: ['Lead Actor/Actress', 'Scriptwriter', 'Sound & Light Engineer', 'Backstage Crew'],
      deadline: 'Aug 16, 2026',
      applicants: [],
    },
  },
  {
    id: 'club-5',
    name: 'PixelCrafters — UI/UX & Design Guild',
    tagLine: 'Where aesthetics meet human-centric engineering.',
    description: 'Design community creating product prototypes, 3D blender animations, branding kits, and interaction designs for campus initiatives.',
    category: 'cultural',
    logo: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1542744094-3a31f272c490?w=800&auto=format&fit=crop&q=80',
    memberCount: 160,
    leadName: 'Aditya Roy',
    leadEmail: 'aditya.design@campus.edu',
    members: [
      { userId: 'usr-1', userName: 'Aryan Sharma', role: 'member', joinedAt: '2024-03-01' },
      { userId: 'usr-4', userName: 'Ananya Sengupta', role: 'core', joinedAt: '2025-08-10' },
    ],
    announcements: [],
    recruitment: {
      isOpen: true,
      title: 'Junior Design Fellowships',
      roles: ['Figma Prototyper', '3D Motion Designer (Blender)', 'Illustrator'],
      deadline: 'Aug 24, 2026',
      applicants: [],
    },
  },
  {
    id: 'club-6',
    name: 'Shutterbugs — Campus Photography & Media Club',
    tagLine: 'Capturing timeless campus memories through the lens.',
    description: 'Documenting every fest, sports league, sunrise over the hostels, and campus biodiversity through professional digital cinematography.',
    category: 'cultural',
    logo: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800&auto=format&fit=crop&q=80',
    memberCount: 95,
    leadName: 'Kabir Ghosh',
    leadEmail: 'kabir.media@campus.edu',
    members: [
      { userId: 'usr-4', userName: 'Ananya Sengupta', role: 'member', joinedAt: '2025-08-12' },
    ],
    announcements: [],
    recruitment: {
      isOpen: false,
      title: 'Recruitment closed',
      roles: [],
      deadline: 'Closed',
      applicants: [],
    },
  },
  {
    id: 'club-7',
    name: 'Striker FC & Campus Football League',
    tagLine: 'Passion, sweat, and glory under the turf floodlights.',
    description: 'Organizers of the Inter-Hostel Football Cup, weekend 7v7 leagues, and college varsity training camp.',
    category: 'sports',
    logo: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=150&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&auto=format&fit=crop&q=80',
    memberCount: 210,
    leadName: 'Rohan Verma',
    leadEmail: 'rohan.verma@campus.edu',
    members: [
      { userId: 'usr-3', userName: 'Rohan Verma', role: 'lead', joinedAt: '2024-08-01' },
    ],
    announcements: [],
    recruitment: {
      isOpen: true,
      title: 'Varsity Team Selection Trials',
      roles: ['Goalkeeper', 'Center Back', 'Winger / Forward'],
      deadline: 'Aug 18, 2026',
      applicants: [],
    },
  },
];

export const mockComplaints: Complaint[] = [
  {
    id: 'cmp-1',
    ticketNumber: 'CC-2026-0842',
    title: 'Wi-Fi Access Point Offline in CS Hub 3rd Floor Labs',
    category: 'wifi',
    priority: 'urgent',
    status: 'in_progress',
    isAnonymous: false,
    authorId: 'usr-1',
    authorName: 'Aryan Sharma',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    buildingId: 'bldg-1',
    buildingName: 'Turing Computer Science Hub',
    roomOrArea: '3rd Floor - Cloud Computing Lab 305',
    description: 'Students in Lab 305 are unable to connect to the eduroam / CampusNet SSID since yesterday evening. Router blinkers are showing solid red LED. Severely affecting ongoing cloud practicals.',
    photoUrl: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=600&auto=format&fit=crop&q=80',
    assignedTo: 'Suresh Kumar (Network IT Lead)',
    assignedTeam: 'Campus IT Infrastructure Group',
    createdAt: '2026-08-09 16:30',
    updatedAt: '2026-08-10 09:15',
    estimatedResolution: 'Today, 02:00 PM (SLA: 24 Hours)',
    timeline: [
      {
        status: 'submitted',
        label: 'Complaint Submitted',
        timestamp: '2026-08-09 16:30',
        note: 'Submitted with photo and tagged to CS Hub Building.',
        updatedBy: 'Aryan Sharma',
      },
      {
        status: 'acknowledged',
        label: 'Acknowledged by Grievance Desk',
        timestamp: '2026-08-09 17:00',
        note: 'Categorized under High Priority IT Service Outage.',
        updatedBy: 'Campus Admin System',
      },
      {
        status: 'assigned',
        label: 'Assigned to Network Operations',
        timestamp: '2026-08-09 18:15',
        note: 'Assigned to engineer Suresh Kumar.',
        updatedBy: 'Dr. K. Raman (Dean)',
      },
      {
        status: 'in_progress',
        label: 'Switch Replacement In Progress',
        timestamp: '2026-08-10 09:15',
        note: 'Faulty Cisco switch identified on floor 3 rack. New gigabit switch being configured and patched.',
        updatedBy: 'Suresh Kumar (Network IT Lead)',
      },
    ],
    upvotes: 18,
    upvotedByUserIds: ['usr-1', 'usr-2', 'usr-3', 'usr-4'],
    adminNotes: 'Switch hardware failure. Replacement unit drawn from central stores inventory.',
  },
  {
    id: 'cmp-2',
    ticketNumber: 'CC-2026-0839',
    title: 'Water Purifier RO Filter Alarm Beeping in Raman Hostel Block A',
    category: 'hostel',
    priority: 'high',
    status: 'assigned',
    isAnonymous: false,
    authorId: 'usr-3',
    authorName: 'Rohan Verma',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    buildingId: 'bldg-7',
    buildingName: 'Raman Boys Hostel Blocks (A & B)',
    roomOrArea: 'Block A, 3rd Floor Water Station',
    description: 'The commercial Kent RO purifier is displaying continuous filter replacement alarm and dispensing water at a very low trickle. Over 60 hostel residents rely on this station.',
    photoUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&auto=format&fit=crop&q=80',
    assignedTo: 'Mahesh Chander (Hostel Estate Supervisor)',
    assignedTeam: 'Hostel Maintenance & Plumbing Cell',
    createdAt: '2026-08-09 10:15',
    updatedAt: '2026-08-09 14:00',
    estimatedResolution: 'Tomorrow, 11:00 AM (SLA: 48 Hours)',
    timeline: [
      {
        status: 'submitted',
        label: 'Complaint Submitted',
        timestamp: '2026-08-09 10:15',
        note: 'Logged via Hostel Resident Portal.',
        updatedBy: 'Rohan Verma',
      },
      {
        status: 'acknowledged',
        label: 'Acknowledged',
        timestamp: '2026-08-09 11:00',
        updatedBy: 'Admin Desk',
      },
      {
        status: 'assigned',
        label: 'Assigned to Plumbing & RO Maintenance',
        timestamp: '2026-08-09 14:00',
        note: 'RO technician vendor requested to visit Raman Hostel Block A.',
        updatedBy: 'Hostel Warden Office',
      },
    ],
    upvotes: 24,
    upvotedByUserIds: ['usr-1', 'usr-3'],
  },
  {
    id: 'cmp-3',
    ticketNumber: 'CC-2026-0820',
    title: 'High-Pitch Noise from Central AC Unit in Library Silent Reading Hall',
    category: 'academic',
    priority: 'medium',
    status: 'resolved',
    isAnonymous: false,
    authorId: 'usr-2',
    authorName: 'Priya Patel',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    buildingId: 'bldg-3',
    buildingName: 'Ramanujan Central Library',
    roomOrArea: '1st Floor Silent Reading Atrium (North Wing)',
    description: 'AC vent #4 has a loose fan belt creating a shrill metallic buzzing sound, disturbing students studying for GATE and semester exams.',
    assignedTo: 'Ramesh Verma (HVAC Team)',
    assignedTeam: 'Central Facilities & HVAC',
    createdAt: '2026-08-07 11:00',
    updatedAt: '2026-08-08 16:30',
    estimatedResolution: 'Resolved on Schedule',
    timeline: [
      { status: 'submitted', label: 'Submitted', timestamp: '2026-08-07 11:00', updatedBy: 'Priya Patel' },
      { status: 'acknowledged', label: 'Acknowledged', timestamp: '2026-08-07 11:30', updatedBy: 'Library Warden' },
      { status: 'assigned', label: 'Assigned to HVAC', timestamp: '2026-08-07 14:00', updatedBy: 'Facilities Office' },
      { status: 'in_progress', label: 'Duct Inspection Underway', timestamp: '2026-08-08 10:00', updatedBy: 'HVAC Team' },
      {
        status: 'resolved',
        label: 'Resolved & Tested',
        timestamp: '2026-08-08 16:30',
        note: 'Replaced worn fan belt and tightened damper mounting bolts. Decibel level tested under 35dB.',
        updatedBy: 'Ramesh Verma',
      },
    ],
    upvotes: 35,
    upvotedByUserIds: ['usr-1', 'usr-2', 'usr-4'],
    adminNotes: 'Repaired under quarterly HVAC maintenance contract.',
  },
  {
    id: 'cmp-4',
    ticketNumber: 'CC-2026-0815',
    title: 'Food Quality & Sanitary Hygiene Inspection Request at Annapoorna Food Court',
    category: 'mess',
    priority: 'high',
    status: 'in_progress',
    isAnonymous: true,
    buildingId: 'bldg-4',
    buildingName: 'Annapoorna Central Food Court',
    roomOrArea: 'Counter 3 - South Indian Section',
    description: 'Observed food handlers working without hairnets and gloves during lunch rush hour today. Sambar temperature was lukewarm. Requesting surprise sanitation audit.',
    assignedTo: 'Dr. Sunita Rao (Health & Food Safety Committee)',
    assignedTeam: 'Campus Hygiene & Food Quality Cell',
    createdAt: '2026-08-08 13:45',
    updatedAt: '2026-08-09 11:20',
    estimatedResolution: 'Aug 11, 2026 (SLA: 72 Hours)',
    timeline: [
      { status: 'submitted', label: 'Anonymous Complaint Submitted', timestamp: '2026-08-08 13:45', updatedBy: 'Anonymous Student' },
      { status: 'acknowledged', label: 'Escalated to Food Safety Committee', timestamp: '2026-08-08 15:00', updatedBy: 'Admin Desk' },
      { status: 'in_progress', label: 'Surprise Audit & Vendor Notice Issued', timestamp: '2026-08-09 11:20', note: 'Vendor fined ₹5000 and mandatory food handling certifications demanded within 48h.', updatedBy: 'Dr. Sunita Rao' },
    ],
    upvotes: 48,
    upvotedByUserIds: ['usr-1', 'usr-2', 'usr-3', 'usr-4'],
  },
  {
    id: 'cmp-5',
    ticketNumber: 'CC-2026-0845',
    title: 'Dark Pathway: Streetlight Bulb Blown Out Near Sports Complex Gate 2',
    category: 'security',
    priority: 'urgent',
    status: 'submitted',
    isAnonymous: false,
    authorId: 'usr-4',
    authorName: 'Ananya Sengupta',
    authorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    buildingId: 'bldg-6',
    buildingName: 'Olympic Sports Arena & Turf Ground',
    roomOrArea: 'Perimeter Pathway connecting Sarojini Hostel to SAC',
    description: 'Two consecutive high-mast LED street lamps are not turning on after 7:00 PM. Creates a completely pitch black 80m stretch for students returning to Sarojini Hostel from night library sessions.',
    assignedTeam: 'Electrical Maintenance & Campus Security',
    createdAt: '2026-08-10 08:30',
    updatedAt: '2026-08-10 08:30',
    estimatedResolution: 'Today, 06:00 PM (SLA: 12 Hours)',
    timeline: [
      {
        status: 'submitted',
        label: 'Complaint Submitted',
        timestamp: '2026-08-10 08:30',
        note: 'Flagged for night safety priority.',
        updatedBy: 'Ananya Sengupta',
      },
    ],
    upvotes: 31,
    upvotedByUserIds: ['usr-1', 'usr-2', 'usr-4'],
  },
  {
    id: 'cmp-6',
    ticketNumber: 'CC-2026-0846',
    title: 'Washing Machine #3 in Sarojini Hostel D-Block Drum Jammed',
    category: 'hostel',
    priority: 'medium',
    status: 'submitted',
    isAnonymous: false,
    authorId: 'usr-4',
    authorName: 'Ananya Sengupta',
    authorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    buildingId: 'bldg-8',
    buildingName: 'Sarojini Girls Hostel Blocks (C & D)',
    roomOrArea: 'Block D, Ground Floor Laundry Bay',
    description: 'The IFB front-loading washer error code E04 shows drum error and locked door. Water draining is stuck.',
    assignedTeam: 'Hostel Maintenance & Appliances',
    createdAt: '2026-08-10 09:00',
    updatedAt: '2026-08-10 09:00',
    estimatedResolution: 'Aug 12, 2026 (SLA: 48 Hours)',
    timeline: [
      { status: 'submitted', label: 'Submitted', timestamp: '2026-08-10 09:00', updatedBy: 'Ananya Sengupta' },
    ],
    upvotes: 12,
    upvotedByUserIds: ['usr-4'],
  },
];

export const mockNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    userId: 'usr-1',
    title: 'Activity Joined 🎉',
    message: 'Ananya Sengupta joined your Smart India Hackathon Squad.',
    type: 'activity',
    timestamp: '15 minutes ago',
    isRead: false,
    link: 'activities',
    priority: 'normal',
  },
  {
    id: 'notif-2',
    userId: 'usr-1',
    title: 'Complaint Update ⚡',
    message: 'Your ticket CC-2026-0842 (Wi-Fi CS Hub) is now In Progress by Suresh Kumar.',
    type: 'complaint',
    timestamp: '2 hours ago',
    isRead: false,
    link: 'campuscare',
    priority: 'high',
  },
  {
    id: 'notif-3',
    userId: 'usr-1',
    title: 'Event Reminder 📅',
    message: 'Google Gemini AI Masterclass is starting in 2 days. Venue: CS Hub Room 204.',
    type: 'event',
    timestamp: '5 hours ago',
    isRead: true,
    link: 'events',
    priority: 'normal',
  },
  {
    id: 'notif-4',
    userId: 'usr-1',
    title: 'Club Announcement 📢',
    message: 'CodeNexus posted: HackNova 2026 Problem Statements are LIVE!',
    type: 'club',
    timestamp: 'Yesterday',
    isRead: true,
    link: 'clubs',
    priority: 'normal',
  },
];

export const mockEmergencyAlert: EmergencyAlert = {
  id: 'alert-1',
  title: '⚠️ Heavy Rainfall & Waterlogging Campus Advisory',
  description: 'Due to continuous torrential rainfall forecasted by MET department for the next 6 hours, all evening outdoor sports activities are temporarily suspended. Shuttles between Hostels and Central Library will operate every 10 minutes.',
  level: 'warning',
  issuedBy: 'Office of Dean (Student Welfare & Campus Safety)',
  issuedAt: '2026-08-10 08:00 AM',
  isActive: true,
  instructions: [
    'Avoid low-lying walkways near South Lake and Sports Field.',
    'Use electric campus shuttle buses available at Hostel Porch.',
    'For 24/7 emergency medical or security transit assistance, call Campus Control Room at Ext: 4444 / +91-98765-43210.',
  ],
};
