# Rich initial dataset for CampusConnect ecosystem

MOCK_CAMPUS_BUILDINGS = [
    {
        "id": "bld_eng_1",
        "name": "Alan Turing Computer Science Block",
        "code": "CS-01",
        "category": "academic",
        "position": {"x": 22, "y": 30},
        "size": {"width": 14, "height": 12},
        "floors": 4,
        "description": "Houses CS, AI & Data Science labs, robotics center, and seminar auditoriums.",
        "image": "https://images.unsplash.com/photo-1562774053-701939374585?w=600&auto=format&fit=crop&q=80",
        "amenities": ["High-Speed Wi-Fi", "GPU Lab", "Cafeteria Kiosk", "Discussion Rooms"],
        "wifiRating": 4.8,
        "openHours": "07:30 AM - 10:00 PM",
        "activeComplaintsCount": 2,
    },
    {
        "id": "bld_lib_1",
        "name": "Rabindranath Tagore Central Library",
        "code": "LIB-01",
        "category": "library",
        "position": {"x": 50, "y": 48},
        "size": {"width": 16, "height": 14},
        "floors": 3,
        "description": "Quiet study zones, 24/7 reading hall, digital archive terminal, and coffee lounge.",
        "image": "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=600&auto=format&fit=crop&q=80",
        "amenities": ["24x7 Reading Room", "Silent Zone", "Air Conditioned", "Printing Service"],
        "wifiRating": 4.9,
        "openHours": "24 Hours (Digital Access)",
        "activeComplaintsCount": 0,
    },
    {
        "id": "bld_sports_1",
        "name": "Major Dhyan Chand Sports Complex",
        "code": "SPT-01",
        "category": "sports",
        "position": {"x": 78, "y": 28},
        "size": {"width": 18, "height": 16},
        "floors": 2,
        "description": "Olympic-sized indoor basketball court, badminton arenas, gymnasium, and synthetic turf field.",
        "image": "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&auto=format&fit=crop&q=80",
        "amenities": ["Indoor Arena", "Gymnasium", "Locker Rooms", "First Aid Station"],
        "wifiRating": 3.9,
        "openHours": "05:30 AM - 09:30 PM",
        "activeComplaintsCount": 1,
    },
    {
        "id": "bld_hostel_b",
        "name": "Aryabhata Boys Residence Hall",
        "code": "HST-B1",
        "category": "hostel",
        "position": {"x": 20, "y": 72},
        "size": {"width": 16, "height": 15},
        "floors": 5,
        "description": "500-capacity undergraduate boys hostel with common recreation room and laundry facility.",
        "image": "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600&auto=format&fit=crop&q=80",
        "amenities": ["Mess Hall", "Washing Machines", "Table Tennis", "Night Canteen"],
        "wifiRating": 4.1,
        "openHours": "Student Residence (Card Access)",
        "activeComplaintsCount": 3,
    },
    {
        "id": "bld_hostel_g",
        "name": "Kalpana Chawla Girls Residence Hall",
        "code": "HST-G1",
        "category": "hostel",
        "position": {"x": 80, "y": 70},
        "size": {"width": 16, "height": 15},
        "floors": 5,
        "description": "Modern hostel for women with secured biometric gates, reading room, and recreational garden.",
        "image": "https://images.unsplash.com/photo-1596276020587-8044fe049813?w=600&auto=format&fit=crop&q=80",
        "amenities": ["Biometric Security", "Fitness Studio", "Reading Lounge", "RO Water"],
        "wifiRating": 4.4,
        "openHours": "Student Residence (Card Access)",
        "activeComplaintsCount": 1,
    },
    {
        "id": "bld_food_1",
        "name": "Campus Student Center & Food Court",
        "code": "FC-01",
        "category": "food",
        "position": {"x": 50, "y": 76},
        "size": {"width": 15, "height": 12},
        "floors": 2,
        "description": "Multi-cuisine student cafeteria, stationery outlet, post desk, and outdoor patio.",
        "image": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&auto=format&fit=crop&q=80",
        "amenities": ["Food Court", "ATM", "Stationery", "Patio Seating"],
        "wifiRating": 4.6,
        "openHours": "08:00 AM - 11:00 PM",
        "activeComplaintsCount": 0,
    }
]

MOCK_EMERGENCY_ALERT = {
    "id": "em_001",
    "title": "Severe Weather Advisory & Campus Safety Protocol",
    "description": "Heavy monsoon rainfall expected between 04:00 PM and 08:00 PM. Evening outdoor sports sessions are suspended. Please use sheltered walkways.",
    "level": "advisory",
    "issuedBy": "Campus Security & Safety Office",
    "issuedAt": "10 minutes ago",
    "isActive": True,
    "instructions": [
        "Avoid low-lying pathways near East Gate.",
        "Inter-block battery shuttles running on schedule till 10 PM.",
        "Emergency security helpline: +91 (800) 555-0199"
    ]
}
